/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DropUnlockRouteImport } from './routes/drop-unlock'
import { Route as DropRouteImport } from './routes/drop'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DSlugRouteImport } from './routes/d.$slug'
import { Route as CSlugRouteImport } from './routes/c.$slug'

const DropUnlockRoute = DropUnlockRouteImport.update({
  id: '/drop-unlock',
  path: '/drop-unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const DropRoute = DropRouteImport.update({
  id: '/drop',
  path: '/drop',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DSlugRoute = DSlugRouteImport.update({
  id: '/d/$slug',
  path: '/d/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CSlugRoute = CSlugRouteImport.update({
  id: '/c/$slug',
  path: '/c/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/drop': typeof DropRoute
  '/drop-unlock': typeof DropUnlockRoute
  '/c/$slug': typeof CSlugRoute
  '/d/$slug': typeof DSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/drop': typeof DropRoute
  '/drop-unlock': typeof DropUnlockRoute
  '/c/$slug': typeof CSlugRoute
  '/d/$slug': typeof DSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/drop': typeof DropRoute
  '/drop-unlock': typeof DropUnlockRoute
  '/c/$slug': typeof CSlugRoute
  '/d/$slug': typeof DSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/drop' | '/drop-unlock' | '/c/$slug' | '/d/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/drop' | '/drop-unlock' | '/c/$slug' | '/d/$slug'
  id: '__root__' | '/' | '/drop' | '/drop-unlock' | '/c/$slug' | '/d/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DropRoute: typeof DropRoute
  DropUnlockRoute: typeof DropUnlockRoute
  CSlugRoute: typeof CSlugRoute
  DSlugRoute: typeof DSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/drop-unlock': {
      id: '/drop-unlock'
      path: '/drop-unlock'
      fullPath: '/drop-unlock'
      preLoaderRoute: typeof DropUnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drop': {
      id: '/drop'
      path: '/drop'
      fullPath: '/drop'
      preLoaderRoute: typeof DropRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/d/$slug': {
      id: '/d/$slug'
      path: '/d/$slug'
      fullPath: '/d/$slug'
      preLoaderRoute: typeof DSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug': {
      id: '/c/$slug'
      path: '/c/$slug'
      fullPath: '/c/$slug'
      preLoaderRoute: typeof CSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DropRoute: DropRoute,
  DropUnlockRoute: DropUnlockRoute,
  CSlugRoute: CSlugRoute,
  DSlugRoute: DSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
